### PR TITLE
Update Catch to version v2.13.7

### PR DESCRIPTION
**Pull request by shr-project**
Includes 2 commits from https://github.com/AIS-Bonn/catch_ros/pull/12 and another update on top of it to fix build with glibc-2.34.

### CODE REVIEW

**Comment by xqms** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Comment by xqms** [comment]
We got the CI running again (thanks @nuclearsandwich!). I'll do a quick test with two downstream packages and then we're set for merging.

**Comment by xqms** [comment]
Everything looks good. I encountered a small issue where the local (newer) catch_ros version clashes with older ones installed via APT, leading to linking errors in downstream packages such as
```
/opt/ros/noetic/include/catch_ros/catch.hpp:1830: undefined reference to `Catch::Capturer::captureValue(unsigned long, Catch::StringRef)'
```

I'll try to at least detect this issue and provide a more meaningful error message, but probably in a separate PR.

**Comment by xqms** [comment]
Turns out the issue I mentioned is a problem in downstream packages (see e.g. https://github.com/AIS-Bonn/nimbro_network/issues/19). I'll fix that there.

Thanks for your contribution!
